/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicadosRouteImport } from './routes/publicados'
import { Route as NovaPublicacaoRouteImport } from './routes/nova-publicacao'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as AgendadosRouteImport } from './routes/agendados'
import { Route as IndexRouteImport } from './routes/index'

const PublicadosRoute = PublicadosRouteImport.update({
  id: '/publicados',
  path: '/publicados',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPublicacaoRoute = NovaPublicacaoRouteImport.update({
  id: '/nova-publicacao',
  path: '/nova-publicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendadosRoute = AgendadosRouteImport.update({
  id: '/agendados',
  path: '/agendados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendados': typeof AgendadosRoute
  '/contas': typeof ContasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/nova-publicacao': typeof NovaPublicacaoRoute
  '/publicados': typeof PublicadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendados': typeof AgendadosRoute
  '/contas': typeof ContasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/nova-publicacao': typeof NovaPublicacaoRoute
  '/publicados': typeof PublicadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendados': typeof AgendadosRoute
  '/contas': typeof ContasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/nova-publicacao': typeof NovaPublicacaoRoute
  '/publicados': typeof PublicadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendados'
    | '/contas'
    | '/dashboard'
    | '/login'
    | '/metricas'
    | '/nova-publicacao'
    | '/publicados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendados'
    | '/contas'
    | '/dashboard'
    | '/login'
    | '/metricas'
    | '/nova-publicacao'
    | '/publicados'
  id:
    | '__root__'
    | '/'
    | '/agendados'
    | '/contas'
    | '/dashboard'
    | '/login'
    | '/metricas'
    | '/nova-publicacao'
    | '/publicados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendadosRoute: typeof AgendadosRoute
  ContasRoute: typeof ContasRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MetricasRoute: typeof MetricasRoute
  NovaPublicacaoRoute: typeof NovaPublicacaoRoute
  PublicadosRoute: typeof PublicadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publicados': {
      id: '/publicados'
      path: '/publicados'
      fullPath: '/publicados'
      preLoaderRoute: typeof PublicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-publicacao': {
      id: '/nova-publicacao'
      path: '/nova-publicacao'
      fullPath: '/nova-publicacao'
      preLoaderRoute: typeof NovaPublicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendados': {
      id: '/agendados'
      path: '/agendados'
      fullPath: '/agendados'
      preLoaderRoute: typeof AgendadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendadosRoute: AgendadosRoute,
  ContasRoute: ContasRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MetricasRoute: MetricasRoute,
  NovaPublicacaoRoute: NovaPublicacaoRoute,
  PublicadosRoute: PublicadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
